lib/Service/SynchronizationService.php

Solves a mismatch between ui and backend on configuration naming

Fix for resultsPosition in stead of objects position

---

appinfo/info.xml
lib/Cron/ActionTask.php
lib/Cron/LogCleanUpTask.php
lib/Db/CallLogMapper.php
lib/Migration/Version1Date20241206095007.php
lib/Service/CallService.php

- Run jobs at given interval
- Store logRetention and errorRetention-fields correctly
- Store expiry of logs
- Remove expired logs

Fixes on jobs and log cleanup

---

lib/Db/SynchronizationContractMapper.php
lib/EventListener/ObjectEventListener.php
lib/Service/SynchronizationService.php

This is a fix to force the recreation of an object if it has been removed in open register

Handeling object removal

---

lib/Controller/EndpointsController.php
lib/Service/AuthorizationService.php
lib/Service/EndpointService.php

Also contains a custom CORS implementation to workaround CORS not being accepted when using OAuth by the default implementation.
Known issue: The frontend can not yet set the users egligible for logging in for rules, therefore these checks are for now disabled

Enable OAuth validation

---

lib/Service/EndpointService.php
lib/Service/SynchronizationService.php

Temporary fix, we should just remove the if statement in my opinion
- also includes: Fix synchronization result response 'found' to show 1 if _object is used

Added a mapResults option for rule config to map results / pagination

---

lib/Service/EndpointService.php
lib/Service/SynchronizationService.php

Dev to main

---

lib/Controller/EndpointsController.php
lib/Http/XMLResponse.php
lib/Service/EndpointService.php
tests/Http/XMLResponseTest.php

Also includes changes to fix xsi:... @attribute tags being replaced with xml:...

Fix html entity encoded characters in xml response by decoding them

---

.github/workflows/phpcs.yml
lib/Service/ImportService.php

also includes:
- Filter out lastRun and nextRun fields when importing a config.json file

Let's ignore branches main/master for checkstyle / php-cs workflow

---

lib/Controller/EndpointsController.php
lib/Service/EndpointService.php
lib/Service/SynchronizationService.php

Also has a fix for delete endpoints and added a catch if multiple endpoints found for the same path

Refactor extendEntity to renderEntity

---

lib/Controller/EndpointsController.php
lib/Db/EndpointMapper.php
lib/Service/EndpointService.php
lib/Service/StorageService.php
website/docs/rules.md

Also: fix the file parts rules in a way that we can accept fileparts on multipart/form-data in PUT requests

Add the functionality for a download rule

---

configurations/xxllnc-zgw/rules/Rule-Fetch file zaaksysteem -_ zgw-v0.0.1.json
lib/Service/EndpointService.php
lib/Service/SynchronizationService.php
src/modals/Rule/EditRule.vue

Added different ways of passing down file context with extra configuration options

Refactor fetch file rule

---

.github/workflows/beta-release.yaml

Same workflow for beta-release as the Open Registers

Create beta-release.yaml for beta releases.

---

lib/Service/RuleService.php

Also: add 'Bron' property to generated objects and rename Pakketten-folder to Applications-folder

Select voorziening based upon VoorzieningGebruiken

---

composer.json
composer.lock
lib/AppInfo/Application.php
lib/EventListener/ViewUpdatedOrCreatedEventListener.php
lib/Service/EndpointService.php
lib/Service/RuleService.php
lib/Service/SoftwareCatalogueService.php

Split connecting view nodes and connections to elements respectively relationships in a concurrent manner.

Connect views concurrent

---

lib/AppInfo/Application.php
lib/EventListener/ViewDeletedEventListener.php
lib/Service/SoftwareCatalogueService.php

also, add model id to extended views

Remove deleted views from extended views

---

appinfo/info.xml
lib/Service/EndpointService.php

Also, allow Nextcloud 31 and 32

Set proper status codes for POST and DELETE methods

---

lib/Service/SynchronizationService.php
website/docs/async-file-fetching.md
website/docs/examples/parallel-timing-example.md
website/docs/parallel-page-fetching.md
website/docs/synchronization-timing.md

From 60.000 tot 6.000 ms for 20 cases including files

Speeding up the synchronisation 

---

lib/Service/ConfigurationHandlers/MappingHandler.php
lib/Service/ConfigurationHandlers/SynchronizationHandler.php
lib/Service/ConfigurationService.php

Also: fix exporting mapping slugs within synchronizations.

Export mappings that are called within mappings

---

lib/Service/MappingService.php

Make mapping error clare

---

lib/Controller/UserController.php
lib/Service/UserService.php

And some loging the better grap the problem if it keeps continuing

Fix for memory issues on user login

---

lib/Service/CallService.php
lib/Service/ConfigurationHandlers/SynchronizationHandler.php
lib/Service/SOAPService.php

Also fix loading the SOAPService, and off cases in the SOAPService

Small fixes on loading Synchronizations
